'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ASPxPivotGrid_GroupFilter


	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ASPxRadioButtonList1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxRadioButtonList1 As Global.DevExpress.Web.ASPxEditors.ASPxRadioButtonList

		''' <summary>
		''' ASPxPivotGrid1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

		''' <summary>
		''' fieldShippedYear control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldShippedYear As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

		''' <summary>
		''' fieldProductSales control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldProductSales As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

		''' <summary>
		''' fieldCategoryName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldCategoryName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

		''' <summary>
		''' fieldShippedMonth control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldShippedMonth As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

		''' <summary>
		''' fieldShippedDay control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fieldShippedDay As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

		''' <summary>
		''' AccessDataSource1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected AccessDataSource1 As Global.System.Web.UI.WebControls.AccessDataSource
	End Class
End Namespace
